### ISSUE TITLE
DelegationEventFunction runtime issue after AccessTokenClient v.1.1.4 update

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-authorization#444]
### Description of the bug

After patching of AccessTokenClient from version 1.1.3 to 1.1.4 the function throws runtime exceptions on 'Microsoft.Extensions.Logging.ILogger'. 

```
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger`1[Altinn.Platform.Authorization.Functions.Clients.BridgeClient]' while attempting to activate 'Altinn.Platform.Authorization.Functions.Clients.BridgeClient'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method431(Closure , IServiceProvider , Object[] )
   at Microsoft.Extensions.Http.DefaultTypedHttpClientFactory`1.CreateClient(HttpClient httpClient)
```

### Steps To Reproduce

Perform any App delegation or revocation triggering a new delegation event to be queued for syncing with Altinn 2

**Comment by jonkjetiloye** [comment]
Solved by rolling back AccessTokenClient to 1.1.3 as the issue seems to be with the sub-dependency upgrade of Microsoft.Extensions.Logging.Abstractions to version 7.0.0
